[package]
name = "fqkit"
version = "0.2.6"
edition = "2021"
authors = ["sharkLoc <mmtinfo@163.com>"]
rust-version = "1.65.0"
homepage = "https://github.com/sharkLoc/fqkit"
description = "fqkit: a simple program for fastq file manipulation"
keywords = ["fastq", "reads","bio", "hts", "barcode"]
readme = "README.md"
license = "GPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
bio = "1.0.0"
chrono = "0.4.30"
clap = { version = "4.0.18", features = ["derive"] }
env_logger = "0.10.0"
flate2 = "1.0.24"
log = "0.4.20"
plotters = "0.3.4"
rand = "0.8.5"
rand_pcg = "0.3.1"
regex = "1.9.5"
